const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const app = express();
const PORT = process.env.PORT || 8080;

// -- Middleware --
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

// -- Storage Configuration for Cloud Run --
// CRITICAL FIX: Cloud Run file system is read-only except for /tmp
// We store uploads in /tmp/uploads which consumes Container Memory (RAM).
const uploadDir = path.join('/tmp', 'uploads');

if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

console.log(`Storage directory set to: ${uploadDir}`);

// Serve uploaded videos statically
// Note: In Cloud Run, files in /tmp are lost if the instance restarts.
app.use('/uploads', express.static(uploadDir));

// Multer for file uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    // Sanitize filename to simple uuid
    const ext = path.extname(file.originalname);
    cb(null, `${uuidv4()}${ext}`);
  }
});

// Limit file size to 3GB
const upload = multer({ 
  storage,
  limits: { fileSize: 3000 * 1024 * 1024 } 
});

// -- In-Memory State --
// WARNING: This resets if the container restarts.
const tournaments = {}; 

// -- Routes --

// 1. Health Check
app.get('/api/health', (req, res) => res.send('OK'));

// 2. Upload Video
// Added Error Handling Wrapper for Multer
app.post('/api/upload', (req, res) => {
  const uploadSingle = upload.single('video');

  uploadSingle(req, res, function (err) {
    if (err instanceof multer.MulterError) {
      console.error("Multer Error:", err);
      return res.status(500).json({ error: err.message });
    } else if (err) {
      console.error("Unknown Upload Error:", err);
      return res.status(500).json({ error: "Unknown upload error" });
    }

    // Success
    if (!req.file) {
      console.error("Upload failed: No file received");
      return res.status(400).json({ error: 'No video file provided' });
    }
    
    console.log(`File uploaded successfully: ${req.file.filename} size: ${(req.file.size / 1024 / 1024).toFixed(2)} MB`);

    const publicUrl = `/uploads/${req.file.filename}`;
    res.json({ 
      url: publicUrl, 
      filename: req.file.filename,
      originalName: req.file.originalname 
    });
  });
});

// 3. Create Tournament
app.post('/api/tournaments', (req, res) => {
  try {
    const { name, hostId, videos } = req.body;
    
    if (!name || !videos || videos.length === 0) {
      return res.status(400).json({ error: 'Invalid data' });
    }

    const code = Math.random().toString(36).substring(2, 7).toUpperCase();
    
    tournaments[code] = {
      id: code,
      name,
      hostId,
      videos,
      createdAt: Date.now(),
      votes: [] 
    };

    console.log(`Tournament created: ${code}`);
    res.json(tournaments[code]);
  } catch (e) {
    console.error("Error creating tournament:", e);
    res.status(500).json({ error: "Internal Server Error" });
  }
});

// 4. Get Tournament
app.get('/api/tournaments/:code', (req, res) => {
  const code = req.params.code.toUpperCase();
  const tournament = tournaments[code];
  
  if (!tournament) {
    return res.status(404).json({ error: 'Tournament not found' });
  }
  
  res.json(tournament);
});

// 5. Submit Vote
app.post('/api/tournaments/:code/vote', (req, res) => {
  const code = req.params.code.toUpperCase();
  const { voteRecord } = req.body;
  
  if (tournaments[code]) {
    tournaments[code].votes.push(voteRecord);
    res.json({ success: true });
  } else {
    res.status(404).json({ error: 'Tournament not found' });
  }
});

// 6. Get Results
app.get('/api/tournaments/:code/results', (req, res) => {
  const code = req.params.code.toUpperCase();
  if (tournaments[code]) {
    res.json({ 
      votes: tournaments[code].votes,
      videos: tournaments[code].videos 
    });
  } else {
    res.status(404).json({ error: 'Tournament not found' });
  }
});

// -- Serve Frontend (Vite Build) --
// Serve the 'dist' folder generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// SPA Fallback: Return index.html for any unknown route
app.get('*', (req, res) => {
  // Check if we are asking for API specifically to avoid returning HTML for 404 API calls
  if (req.path.startsWith('/api')) {
    return res.status(404).json({ error: 'API route not found' });
  }
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Create Server Instance
const server = app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
  console.log(`Upload directory: ${uploadDir}`);
  console.log(`Max Upload Size: 3GB`);
});

// CRITICAL for Large Uploads:
// Node.js defaults to 2 minutes (120000ms). 3GB uploads will likely take longer.
// Setting timeout to 1 Hour (3600000 ms).
server.keepAliveTimeout = 3600000;
server.headersTimeout = 3600000;
server.timeout = 3600000;